import { BugReport, DashboardStats, TestCase } from '@/types';

export const mockBugs: BugReport[] = [
  {
    id: 'bug-001',
    rawInput: 'Login page crashes when using SSO with corporate account. White screen appears after OAuth redirect.',
    title: 'SSO Login Crash on OAuth Callback',
    description: 'Users experience an unhandled exception when signing in via SSO. The application crashes after the OAuth callback.',
    severity: 'CRITICAL',
    priority: 'P0',
    status: 'OPEN',
    stepsToReproduce: ['Navigate to /auth/login', 'Click "Sign in with SSO"', 'Complete IdP authentication', 'Observe crash on redirect'],
    expectedResult: 'User is authenticated and redirected to dashboard',
    actualResult: 'White screen with TypeError in console',
    environment: { os: 'Windows 11', browser: 'Chrome 120', version: 'v2.4.1' },
    rootCauseHypotheses: ['OAuth token schema change', 'Race condition in token storage', 'Missing null check on response'],
    affectedModules: ['Authentication', 'Session Management'],
    qualityScore: 87,
    duplicateOfId: null,
    screenshotUrls: [],
    logContent: null,
    aiAnalysis: { summary: 'OAuth callback handler fails on token destructuring', technicalDetails: 'Unhandled undefined access on token response', suggestedFix: 'Add defensive null checks', relatedAreas: ['Token refresh', 'Session persistence'], confidence: 0.85 },
    impactPrediction: { userImpact: 'CRITICAL', affectedModules: ['Authentication'], estimatedUsersImpacted: '35% enterprise users', businessImpact: 'Blocks enterprise access', testCoverageSuggestions: ['SSO flow tests', 'Token refresh edge cases'] },
    tags: ['sso', 'crash', 'authentication', 'blocker'],
    clusterId: null,
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 3600000).toISOString(),
  },
  {
    id: 'bug-002',
    rawInput: 'Payment form shows wrong currency symbol after switching regions. Amount displays correctly but symbol is from previous region.',
    title: 'Currency Symbol Not Updating on Region Change',
    description: 'The payment form retains the previous region currency symbol when users switch their billing region.',
    severity: 'HIGH',
    priority: 'P1',
    status: 'OPEN',
    stepsToReproduce: ['Go to Settings > Billing', 'Change region from US to EU', 'Navigate to payment form', 'Observe $ symbol instead of €'],
    expectedResult: 'Currency symbol updates to match selected region',
    actualResult: 'Previous region currency symbol persists until page refresh',
    environment: { os: 'macOS 14', browser: 'Safari 17', version: 'v2.4.1' },
    rootCauseHypotheses: ['Stale state in currency context', 'Locale not propagating to form', 'Cached currency formatter'],
    affectedModules: ['Billing', 'Localization', 'Payment Processing'],
    qualityScore: 92,
    duplicateOfId: null,
    screenshotUrls: [],
    logContent: null,
    aiAnalysis: { summary: 'Currency context not refreshed on region change', technicalDetails: 'React context holding stale locale value', suggestedFix: 'Force re-render of currency formatter on region update', relatedAreas: ['i18n', 'Payment form'], confidence: 0.78 },
    impactPrediction: { userImpact: 'HIGH', affectedModules: ['Billing', 'Localization'], estimatedUsersImpacted: '15% international users', businessImpact: 'Could lead to payment errors', testCoverageSuggestions: ['Region switching tests', 'Currency display verification'] },
    tags: ['billing', 'localization', 'currency', 'ui'],
    clusterId: null,
    createdAt: new Date(Date.now() - 8 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: 'bug-003',
    rawInput: 'Dashboard charts show no data after midnight UTC. Refresh fixes it but data gap appears in analytics.',
    title: 'Dashboard Data Gap at UTC Midnight Rollover',
    description: 'Real-time dashboard charts display empty state between 00:00-00:05 UTC during the daily data aggregation window.',
    severity: 'MEDIUM',
    priority: 'P2',
    status: 'IN_PROGRESS',
    stepsToReproduce: ['Open dashboard before 23:59 UTC', 'Wait for midnight rollover', 'Observe charts losing data', 'Manual refresh restores data after ~5 min'],
    expectedResult: 'Continuous data display during rollover',
    actualResult: '5-minute data gap visible in charts',
    environment: { os: 'Any', browser: 'Any', version: 'v2.4.0+' },
    rootCauseHypotheses: ['Aggregation job blocks reads', 'Cache invalidation timing', 'Timezone boundary in query logic'],
    affectedModules: ['Dashboard', 'Analytics', 'Data Pipeline'],
    qualityScore: 74,
    duplicateOfId: null,
    screenshotUrls: [],
    logContent: null,
    aiAnalysis: { summary: 'Data aggregation job creates temporary read gap', technicalDetails: 'Cron job at midnight invalidates cache before new aggregation completes', suggestedFix: 'Implement double-buffered aggregation or serve stale data during rollover', relatedAreas: ['Cron jobs', 'Caching layer'], confidence: 0.72 },
    impactPrediction: { userImpact: 'MODERATE', affectedModules: ['Dashboard'], estimatedUsersImpacted: '8% active users during UTC midnight', businessImpact: 'Reduces trust in real-time metrics', testCoverageSuggestions: ['Midnight rollover tests', 'Cache invalidation timing'] },
    tags: ['dashboard', 'analytics', 'data-gap', 'timezone'],
    clusterId: null,
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: 'bug-004',
    rawInput: 'File upload silently fails for files larger than 10MB. No error message shown to user.',
    title: 'Silent Failure on Large File Upload (>10MB)',
    description: 'File uploads exceeding 10MB fail without displaying any error message. The upload spinner completes but the file is not stored.',
    severity: 'HIGH',
    priority: 'P1',
    status: 'OPEN',
    stepsToReproduce: ['Navigate to upload section', 'Select a file >10MB', 'Click upload', 'Observe spinner completes but file missing'],
    expectedResult: 'Clear error message about file size limit or successful upload',
    actualResult: 'Upload appears to succeed but file is not stored',
    environment: { os: 'Any', browser: 'Chrome/Firefox', version: 'v2.3.8+' },
    rootCauseHypotheses: ['Server-side size limit not communicated to client', 'Error response swallowed by catch block', 'Nginx proxy buffering limit'],
    affectedModules: ['File Upload', 'API Gateway', 'Storage'],
    qualityScore: 81,
    duplicateOfId: null,
    screenshotUrls: [],
    logContent: 'Error: Request entity too large (413)',
    aiAnalysis: { summary: 'Server rejects large files but client ignores error', technicalDetails: 'Nginx returns 413 but frontend catch block shows success', suggestedFix: 'Add client-side validation and proper error handling for 413 responses', relatedAreas: ['Nginx config', 'Error handling'], confidence: 0.91 },
    impactPrediction: { userImpact: 'HIGH', affectedModules: ['File Upload'], estimatedUsersImpacted: '20% of users uploading files', businessImpact: 'Data loss risk, user frustration', testCoverageSuggestions: ['File size boundary tests', 'Error message verification'] },
    tags: ['upload', 'file-size', 'silent-failure', 'ux'],
    clusterId: null,
    createdAt: new Date(Date.now() - 48 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 36 * 3600000).toISOString(),
  },
  {
    id: 'bug-005',
    rawInput: 'Search results page shows wrong pagination count after applying filters',
    title: 'Pagination Count Mismatch After Filter Application',
    description: 'The total results count in pagination does not update when filters are applied, showing the unfiltered total.',
    severity: 'LOW',
    priority: 'P3',
    status: 'RESOLVED',
    stepsToReproduce: ['Go to search page', 'Perform a search', 'Apply a category filter', 'Check pagination showing total count'],
    expectedResult: 'Pagination reflects filtered count',
    actualResult: 'Pagination shows unfiltered total',
    environment: { os: 'Any', browser: 'Any', version: 'v2.4.0' },
    rootCauseHypotheses: ['Pagination uses cached total', 'Filter not included in count query'],
    affectedModules: ['Search', 'Pagination'],
    qualityScore: 68,
    duplicateOfId: null,
    screenshotUrls: [],
    logContent: null,
    aiAnalysis: { summary: 'Count query ignores active filters', technicalDetails: 'Separate count endpoint not receiving filter params', suggestedFix: 'Pass filter params to count endpoint', relatedAreas: ['Search API'], confidence: 0.88 },
    impactPrediction: { userImpact: 'LOW', affectedModules: ['Search'], estimatedUsersImpacted: '5% of search users', businessImpact: 'Minor UX confusion', testCoverageSuggestions: ['Filtered search pagination tests'] },
    tags: ['search', 'pagination', 'filters'],
    clusterId: null,
    createdAt: new Date(Date.now() - 96 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 72 * 3600000).toISOString(),
  },
  {
    id: 'bug-006',
    rawInput: 'Mobile navigation menu overlaps content on tablet landscape mode',
    title: 'Navigation Menu Overlap in Tablet Landscape',
    description: 'On tablets in landscape orientation, the hamburger menu expands but overlaps page content without a backdrop.',
    severity: 'MEDIUM',
    priority: 'P2',
    status: 'OPEN',
    stepsToReproduce: ['Open app on tablet', 'Rotate to landscape', 'Open navigation menu', 'Observe content overlap'],
    expectedResult: 'Menu pushes content or has a backdrop overlay',
    actualResult: 'Menu overlaps interactive content elements',
    environment: { os: 'iPadOS 17', browser: 'Safari', device: 'iPad Air', resolution: '2360x1640' },
    rootCauseHypotheses: ['Missing media query for tablet landscape', 'z-index stacking context issue'],
    affectedModules: ['Navigation', 'Responsive Layout'],
    qualityScore: 71,
    duplicateOfId: null,
    screenshotUrls: [],
    logContent: null,
    aiAnalysis: { summary: 'Responsive breakpoint gap for tablet landscape', technicalDetails: 'CSS media queries jump from mobile to desktop without tablet landscape handling', suggestedFix: 'Add intermediate breakpoint for 1024-1280px width range', relatedAreas: ['CSS', 'Responsive design'], confidence: 0.79 },
    impactPrediction: { userImpact: 'MODERATE', affectedModules: ['Navigation'], estimatedUsersImpacted: '12% tablet users', businessImpact: 'Poor UX on tablets', testCoverageSuggestions: ['Tablet viewport testing', 'Orientation change tests'] },
    tags: ['responsive', 'tablet', 'navigation', 'css'],
    clusterId: null,
    createdAt: new Date(Date.now() - 72 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 3600000).toISOString(),
  },
];

export const mockDashboardStats: DashboardStats = {
  totalBugs: 147,
  criticalBugs: 12,
  resolvedBugs: 89,
  avgQualityScore: 76.4,
  severityDistribution: [
    { name: 'Critical', value: 12, color: '#ef4444' },
    { name: 'High', value: 34, color: '#f97316' },
    { name: 'Medium', value: 52, color: '#eab308' },
    { name: 'Low', value: 38, color: '#22c55e' },
    { name: 'Info', value: 11, color: '#3b82f6' },
  ],
  recentBugs: mockBugs.slice(0, 5),
  trendData: [
    { date: 'Mon', bugs: 8, resolved: 5 },
    { date: 'Tue', bugs: 12, resolved: 9 },
    { date: 'Wed', bugs: 6, resolved: 7 },
    { date: 'Thu', bugs: 15, resolved: 11 },
    { date: 'Fri', bugs: 9, resolved: 8 },
    { date: 'Sat', bugs: 4, resolved: 6 },
    { date: 'Sun', bugs: 7, resolved: 4 },
  ],
  topModules: [
    { module: 'Authentication', count: 28 },
    { module: 'Payment Processing', count: 22 },
    { module: 'Dashboard', count: 18 },
    { module: 'File Upload', count: 15 },
    { module: 'Search', count: 13 },
    { module: 'Navigation', count: 11 },
    { module: 'Notifications', count: 9 },
    { module: 'User Profile', count: 7 },
  ],
};

export const mockTestCases: TestCase[] = [
  {
    id: 'tc-001',
    bugReportId: 'bug-001',
    title: 'SSO Login - Valid Corporate Account',
    description: 'Verify successful SSO login with a valid corporate account through OAuth flow',
    steps: ['Navigate to login page', 'Click SSO login button', 'Authenticate with valid corporate credentials', 'Verify redirect to dashboard'],
    expectedResult: 'User is authenticated and sees the dashboard with correct session',
    type: 'regression',
    priority: 'P0',
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'tc-002',
    bugReportId: 'bug-001',
    title: 'SSO Login - Expired Token Handling',
    description: 'Verify proper handling when OAuth returns an expired token',
    steps: ['Initiate SSO login', 'Simulate expired token in OAuth response', 'Verify error handling'],
    expectedResult: 'User sees a clear error message and option to retry',
    type: 'edge_case',
    priority: 'P1',
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'tc-003',
    bugReportId: 'bug-002',
    title: 'Currency Display - Region Switch',
    description: 'Verify currency symbol updates when billing region changes',
    steps: ['Navigate to billing settings', 'Change region from US to EU', 'Check currency symbol in payment form'],
    expectedResult: 'Currency symbol changes from $ to €',
    type: 'regression',
    priority: 'P1',
    createdAt: new Date(Date.now() - 8 * 3600000).toISOString(),
  },
];
